### ISSUE TITLE
问题：我通过docker运行起来之后，缓存目录里只有目录和list文件，没有库文件

### ISSUE THREAD

**Issue by springeye** [goproxy/goproxy.cn#213]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？
没有

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.22.0 darwin/arm64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE='auto'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/develop/Library/Caches/go-build'
GOENV='/Users/develop/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/develop/.gvm/pkgsets/go1.22.0/global/pkg/mod'
GONOPROXY='tiptop.com'
GONOSUMDB='tiptop.com'
GOOS='darwin'
GOPATH='/Users/develop/.gvm/pkgsets/go1.22.0/global'
GOPRIVATE='tiptop.com'
GOPROXY='http://127.0.0.1:8100'
GOROOT='/Users/develop/.gvm/gos/go1.22.0'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/develop/.gvm/gos/go1.22.0/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/develop/workspaces/smoney-cloud/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/7z/ts3_vd810t1dq_hgcz0ttbn80000gn/T/go-build302892491=/tmp/go-build -gno-record-gcc-switches -fno-common'

</pre>
</details>

## 你做了什么？

我通过docker compose 本地运行了一个goproxy,
```yaml
version: '3.9'
services:
  goproxy:
    image: ghcr.io/goproxy/goproxy
    volumes:
      - ./storage/cache:/caches
    ports:
      - 8100:8100
    environment:
      - GOPROXY=https://goproxy.cn
    command: ["server", "--address",":8100","--cacher-dir","/caches"]
```

## 你期望看到的结果是什么？

我期望缓存目录里有拉去过的文件

## 你实际看到的结果是什么？

只有对应的目录和目录里的list文件
<img width="312" alt="image" src="https://github.com/goproxy/goproxy.cn/assets/1314740/97f6d7d1-97aa-47b1-983d-2e0ec493a38a">
